#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.sales-repeat-customers', [])
module.controller('WidgetSalesRepeatCustomersCtrl', ($scope, $q, $filter, ImpacWidgetsSvc, ImpacAssets, HighchartsFactory, ImpacUtilities) ->

  w = $scope.widget
  $scope.firstMonthActive = true

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();
  settingsPromises = [$scope.orgDeferred.promise]

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetSalesRepeatCustomers', ->
  return {
    restrict: 'A',
    controller: 'WidgetSalesRepeatCustomersCtrl'
  }
)
