#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.sales-days-between-visits', [])
module.controller('WidgetSalesDaysBetweenVisitsCtrl', ($scope, $q) ->

  w = $scope.widget

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer();
  settingsPromises = [$scope.orgDeferred.promise]

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetSalesDaysBetweenVisits', ->
  return {
    restrict: 'A',
    controller: 'WidgetSalesDaysBetweenVisitsCtrl'
  }
)
