#
# Component generated by Impac! Widget Generator!
#
module = angular.module('impac.components.widgets.sales-days-between-visits', [])
module.controller('WidgetSalesDaysBetweenVisitsCtrl', ($scope, $q, $filter, ChartFormatterSvc) ->

  w = $scope.widget
  $scope.isHistMode = false

  # Define settings
  # --------------------------------------
  $scope.orgDeferred = $q.defer()
  $scope.chartDeferred = $q.defer()
  settingsPromises = [
    $scope.orgDeferred.promise
    $scope.chartDeferred.promise
  ]

  # Widget specific methods
  # --------------------------------------
  w.initContext = ->
    $scope.isDataFound = w.content?

  $scope.toggleHistMode = (histMode) ->
    $scope.isHistMode = histMode

  $scope.getColorByIndex = (index) ->
    ChartFormatterSvc.getColor(index)

  $scope.latestDate = ->
    date = _.last(_.sortBy(w.content.small_chart.dates, String))
    $filter('date')(date, 'dd/MM/yyyy')

  # Chart formating function
  # --------------------------------------
  $scope.drawTrigger = $q.defer()
  w.format = ->
    if $scope.isDataFound
      dates = _.map w.content.small_chart.dates, (date) ->
        $filter('date')(date, 'MMM yy')

      lineOptions = {
        scaleBeginAtZero: true,
        showXLabels: false,
        currency: 'hide'
      }

      lineData = [
        {title: 'Merchant', labels: dates, values: w.content.small_chart.merchant_values},
        {title: 'Competitive Set', labels: dates, values: w.content.small_chart.competitive_values},
        {title: 'Industry', labels: dates, values: w.content.small_chart.industry_values}
      ]

      # init chartData after transletion chages
      chartData = ChartFormatterSvc.lineChart(lineData,lineOptions)

      # calls chart.draw()
      $scope.drawTrigger.notify(chartData)

  # Widget is ready: can trigger the "wait for settings to be ready"
  # --------------------------------------
  $scope.widgetDeferred.resolve(settingsPromises)
)
module.directive('widgetSalesDaysBetweenVisits', ->
  return {
    restrict: 'A',
    controller: 'WidgetSalesDaysBetweenVisitsCtrl'
  }
)
